# Generated by Django 4.2 on 2023-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_item_dish_name_item_dish_price_alter_item_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
